version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8085:8085"
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: vocabulary
      POSTGRES_PASSWORD: vocabulary
      POSTGRES_DB: vocabulary
    volumes:
      - ./dbData:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    environment:
      - BACKEND_HOST=localhost
      - BACKEND_PORT=8085
    volumes:
      - ./ui:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    ports:
      - "3005:3000"
    depends_on:
      - backend