version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      APP_ENV: "docker"
      DBUSER: "user"
      DBPASS: "asd"
      DBHOST: "postgres" # este nombre es el del servicio de postgres. Ese es el endpoint
    ports:
      - "8085:8085"
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: vocabulary
      POSTGRES_PASSWORD: vocabulary
      POSTGRES_DB: vocabulary
      DATABASE_HOST: postgres
      PGPORT: 5435
    volumes:
      - ./dbData:/var/lib/postgresql/data
    ports:
      - "5435:5435"

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    environment:
      - BACKEND_HOST: localhost
      - BACKEND_PORT: 8085
    ports:
      - "3005:3000"
    depends_on:
      - backend
